# Generated by Django 5.2.1 on 2025-06-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок блога", max_length=200, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Введите содержание блога", verbose_name="Содержание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью блога",
                        null=True,
                        upload_to="blog_previews/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания блога", verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Укажите, опубликован ли блог", verbose_name="Опубликовано"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Количество просмотров блога", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["-created_at"],
            },
        ),
    ]
