# Generated by Django 5.2.1 on 2025-06-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите количество просмотров блога", verbose_name="Счетчик просмотров постов"
            ),
        ),
    ]
