# Generated by Django 5.2.3 on 2025-06-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_views_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_unpublish_blog", "Can unpublish blog")],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
