# Generated by Django 5.2.1 on 2025-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Введите описание категории", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите наименование категории продуктов", max_length=100, verbose_name="Наименование"
            ),
        ),
    ]
