# Generated by Django 5.2.1 on 2025-06-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию продукта",
                null=True,
                upload_to="blog/photo",
                verbose_name="Фото",
            ),
        ),
    ]
