# Generated by Django 5.2.3 on 2025-06-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Укажите, опубликован ли продукт", verbose_name="Опубликовано"
            ),
        ),
    ]
